#!/bin/bash

f=/home/feng.zhang/uhost.list
i=0

while read ip desc
do
    if [ -z $ip ] ;then
        continue
    fi
    
    host[$i]=$ip
    
    let line=$i%2
    if [ $line -eq 0 ];then
        echo -ne "\e[1;32m $i: \e[0m\t$desc\t$ip\t"
    else
        echo -e "\e[1;32m $i: \e[0m\t$desc\t$ip"
    fi

    let i=$i+1
done < $f

echo
echo -ne "\e[1;31m Please input Num :\e[0m"
read index
echo -e "\e[1;31m ++++ ${host[$index]} ++++\e[0m"
echo

ssh "feng.zhang@${host[$index]}"
